AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This lambda process the image in order to resize it
Resources:
  TreatImage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: This lambda process the image in order to resize it
      MemorySize: 192
      Timeout: 15
      Role: 'arn:aws:iam::828843326560:role/Lambda-role'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: untreated/
                  - Name: suffix
                    Value: .JPG
        BucketEvent2:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket2
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: untreated/
                  - Name: suffix
                    Value: .png
        BucketEvent3:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket3
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: untreated/
                  - Name: suffix
                    Value: .jpeg
        BucketEvent4:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket4
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: untreated/
                  - Name: suffix
                    Value: .jpg
  Bucket1:
    Type: 'AWS::S3::Bucket'
  Bucket2:
    Type: 'AWS::S3::Bucket'
  Bucket3:
    Type: 'AWS::S3::Bucket'
  Bucket4:
    Type: 'AWS::S3::Bucket'
